title: "お前今日何したんだよ"
summary: "日々の勉強記録  \n 
「お前には関係ないかもしれないけどよ \n 
少なくとも俺は先月の俺よりハッピーだぜ \n 
がんばろうぜ」 \n 
元ネタ様：https://www.tiktok.com/@shanezsociety/video/7215585442677230850"
topics: [メモ, 日記]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
